version: '3'

services:
  hormozgroup:
    container_name: hormozgroup.ir
    build: .
    command: ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8300"]
    volumes:
      - .:/var/www/hormozgroup.ir
    ports:
      - 8300:8300
    restart: unless-stopped
    networks:
      - hormozgroup

  mysql:
    image: mysql:8.0.32
    container_name: hormozgroup_mysql
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .env
    volumes:
      - ./hormozgroup_db_volume/:/var/lib/mysql
    networks:
      - hormozgroup

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=hormozgroup_mysql
      - UPLOAD_LIMIT=300M
    depends_on:
      - mysql
    networks:
      - hormozgroup

networks:
  hormozgroup:
