services:
  hormozgroup:
    container_name: hormozgroup_app
    build: .
    command: ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8300"]
    volumes:
      - .:/var/www/hormozgroup.ir
    ports:
      - 127.0.0.1:8300:8300
    networks:
      - hormozgroup
    env_file:
      - .env
    restart: unless-stopped

  mysql:
    image: mysql:8.0.32
    container_name: hormozgroup-mysql
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .env
    volumes:
      - ./hormozgroup_db_volume/:/var/lib/mysql
    networks:
      - hormozgroup
    restart: unless-stopped

networks:
  hormozgroup:
